# Copyright (c) Mysten Labs, Inc.
# SPDX-License-Identifier: Apache-2.0

query getCurrentEpoch {
    epoch {
        epochId
        totalTransactions
        startTimestamp
        endTimestamp
        referenceGasPrice

        firstCheckpoint: checkpoints(first: 1) {
            nodes {
                sequenceNumber
            }
        }

        validatorSet {
            activeValidators {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                nodes {
                    ...RPC_VALIDATOR_FIELDS
                }
            }
            contents {
                type {
                    repr
                }
                json
                bcs
            }
        }
    }
}

query paginateEpochValidators($id: UInt53!, $after: String) {
    epoch(epochId: $id) {
        validatorSet {
            activeValidators(after: $after) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                nodes {
                    ...RPC_VALIDATOR_FIELDS
                }
            }
        }
    }
}

fragment RPC_VALIDATOR_FIELDS on Validator {
    atRisk
    contents {
        type {
            repr
        }
        json
        bcs
    }
}