// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package sui.rpc.v2;

option java_package = "sui.rpc.v2";
option java_outer_classname = "ArgumentProto";

enum ArgumentKind {
  ARGUMENT_KIND_UNKNOWN = 0;

  // The gas coin.
  ARGUMENT_KIND_GAS = 1;

  // One of the input objects or primitive values (from
  // `ProgrammableTransaction` inputs).
  ARGUMENT_KIND_INPUT = 2;

  // The result of another command (from `ProgrammableTransaction` commands).
  ARGUMENT_KIND_RESULT = 3;
}

// An argument to a programmable transaction command.
message Argument {
  optional ArgumentKind kind = 1;

  // Index of an input when `kind` is `INPUT`.
  optional uint32 input = 2;

  // Index of a result when `kind` is `RESULT`.
  optional uint32 result = 3;

  // Used to access a nested result when `kind` is `RESULT`.
  optional uint32 subresult = 4;
}
