# Copyright (c) Mysten Labs, Inc.
# SPDX-License-Identifier: Apache-2.0

query getLatestSuiSystemState(
    $activeValidatorsFirst: Int
    $activeValidatorsAfter: String
    $activeValidatorsLast: Int
    $activeValidatorsBefore: String
) {
    epoch {
        epochId
        startTimestamp
        endTimestamp
        referenceGasPrice
        fundInflow
        fundOutflow
        fundSize
        liveObjectSetDigest
        netInflow
        totalCheckpoints
        totalGasFees
        totalStakeRewards
        totalStakeSubsidies
        totalTransactions

        protocolConfigs {
            protocolVersion
        }

        systemState {
            type {
                repr
            }
            json
            bcs
        }

        validatorSet {
            activeValidators(
                first: $activeValidatorsFirst
                after: $activeValidatorsAfter
                last: $activeValidatorsLast
                before: $activeValidatorsBefore
            ) {
                pageInfo {
                    hasNextPage
                    hasPreviousPage
                    endCursor
                    startCursor
                }
                nodes {
                    ...RPC_VALIDATOR_FIELDS
                }
            }
            contents {
                type {
                    repr
                }
                json
                bcs
            }
        }
    }
}