// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package sui.rpc.v2;

option java_package = "sui.rpc.v2";
option java_outer_classname = "InputProto";

import "struct_proto.proto";

enum InputKind {
  INPUT_KIND_UNKNOWN = 0;

  // A move value serialized as BCS.
  INPUT_KIND_PURE = 1;

  // A Move object that is either immutable or address owned.
  INPUT_KIND_IMMUTABLE_OR_OWNED = 2;

  // A Move object whose owner is "Shared".
  INPUT_KIND_SHARED = 3;

  // A Move object that is attempted to be received in this transaction.
  INPUT_KIND_RECEIVING = 4;

  // Reservation to withdraw balance from a funds accumulator
  INPUT_KIND_FUNDS_WITHDRAWAL = 5;
}

enum InputMutability {
  INPUT_MUTABILITY_UNKNOWN = 0;
  INPUT_MUTABILITY_IMMUTABLE = 1;
  INPUT_MUTABILITY_MUTABLE = 2;

  // Non-exclusive write is used to allow multiple transactions to
  // simultaneously add disjoint dynamic fields to an object.
  // (Currently only used by settlement transactions).
  INPUT_MUTABILITY_NON_EXCLUSIVE_WRITE = 3;
}

enum FundsWithdrawalSource {
  FUNDS_WITHDRAWAL_SOURCE_UNKNOWN = 0;
  FUNDS_WITHDRAWAL_SOURCE_SENDER = 1;
  FUNDS_WITHDRAWAL_SOURCE_SPONSOR = 2;
}

// An input to a user transaction.
message Input {
  optional InputKind kind = 1;

  // A move value serialized as BCS.
  //
  // For normal operations this is required to be a move primitive type and not contain structs
  // or objects.
  optional bytes pure = 2;

  // `ObjectId` of the object input.
  optional string object_id = 3;

  // Requested version of the input object when `kind` is `IMMUTABLE_OR_OWNED`
  // or `RECEIVING` or if `kind` is `SHARED` this is the initial version of the
  // object when it was shared
  optional uint64 version = 4;

  // The digest of this object.
  optional string digest = 5;

  // Controls whether the caller asks for a mutable reference to the shared
  // object.
  optional bool mutable = 6;

  // NOTE: For backwards compatibility purposes the addition of the new
  // `NON_EXCLUSIVE_WRITE` mutability variant requires providing a new field.
  // The old `mutable` field will continue to be populated and respected as an
  // input for the time being.
  optional InputMutability mutability = 7;

  // Fund Reservation information if `kind` is `FUNDS_WITHDRAWAL`.
  optional FundsWithdrawal funds_withdrawal = 8;

  // A literal value
  //
  // INPUT ONLY
  optional Value literal = 1000;
}

message FundsWithdrawal {
  optional uint64 amount = 1;
  optional string coin_type = 2;
  optional FundsWithdrawalSource source = 3;
}
