name: Release
on:
  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  release:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master'
    environment: Sonatype
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SONATYPE_SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SONATYPE_SIGNING_KEY_PASSWORD }}

      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
        - name: Grant execute permissions to publish script
          run: chmod +x ./scripts/release
        - name: Release to Sonatype (Maven Central)
          shell: bash
          run: ./scripts/release